### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by di1l0o** [RossFabricant/omegapoint#1]
We found a malicious backdoor in versions 0.0.1~0.0.2 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using pip3 install omegapoint==0.0.2 -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/171596775-f0d6d40e-110f-4352-bff9-b2632a269fba.png)

Repair suggestion: delete versions 0.0.1~0.0.2 in PyPI

**Comment by rfabricant-cbp** [comment]
Deleted. Thanks for the notice.
